FROM perl:latest as build-deps
COPY cpanfile .
RUN cpanm --test-only --installdeps . \
    && cpanm -n --installdeps .

FROM perl:slim as test
COPY --from=build-deps /usr/local/ /usr/local
COPY . .
RUN prove -l

FROM perl:slim as runtime
COPY --from=build-deps /usr/local/ /usr/local
COPY . .
RUN cpanm -n .
